### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by darioAnongba** [mit-dci/zkledger#1]
Hello,

I am very much interested in your zkLedger implementation. In the paper it is stated that the source code will be available at "zkledger.org". Sadly the link points to this repository that only contains the paper itself.

How to have access to the implementation?

**Comment by triplewz** [comment]
Hello, have you got the source code?

**Comment by darioAnongba** [comment]
No

**Comment by triplewz** [comment]
Do you have other solutions?

**Comment by darioAnongba** [comment]
What do you mean?

**Comment by triplewz** [comment]
To do the experiment.

**Comment by Nabeelperson** [comment]
@darioAnongba @wz11021324 its finally up!
